apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mu6sejo91-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mu6sejo91-nodejs 
  name: mu6sejo91-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: mu6sejo91-nodejs 
